"""fdfd

Revision ID: 611fa40e2703
Revises: 
Create Date: 2025-05-16 11:41:27.246910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611fa40e2703'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dueño',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_documento', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=60), nullable=True),
    sa.Column('modelo', sa.String(length=60), nullable=True),
    sa.Column('precio', sa.String(length=60), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Producto')
    op.drop_table('categorias')
    op.drop_table('Dueño')
    # ### end Alembic commands ###
